title: Yending
author: Yending
email: yending.uy@gmail.com
description: >-
  Yending es una plataforma de trayectos compartidos diseñada para poner en contacto a conductores y pasajeros. Viajan juntos, cómodos y comparten los gastos. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

